// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_PraPBL_Backend.Data;

#nullable disable

namespace _2026_PraPBL_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209142319_InitialCreateRoom")]
    partial class InitialCreateRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("_2026_PraPBL_Backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Description = "Lantai 2 Gedung D4",
                            IsAvailable = true,
                            Name = "Lab SCADA"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 100,
                            Description = "Lantai 1 Gedung TC",
                            IsAvailable = true,
                            Name = "Ruang Teater"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
